[platformio]
default_envs = cyd-display

[env:cyd-display]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_filters =
    esp32_exception_decoder

board_build.flash_mode = dio
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CYD_DISPLAY_NODE
    -D USER_SETUP_LOADED
    -D ILI9341_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD
    -D SPI_FREQUENCY=40000000
    -I include
    -I include/config
    -I include/protocols

lib_deps =
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson

upload_protocol = esptool

; OTA upload - enable after first USB flash
; upload_protocol = espota
; upload_port = rover-cyd.local
; upload_flags =
;     --auth=rover-ota-2025
